/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.meta.pr1;

import javax.swing.JMenuItem;

/**
 *
 * @author David
 */
public class Consola extends javax.swing.JFrame {

    int eleccion;
    
    
    /**
     * Creates new form Consola
     */
    public Consola() {
        initComponents();
        this.eleccion = 0;
        this.jProgressBarEstado.setVisible(false);
    }

    
    public void presentarSalida (String mensaje) {
        if (isVisible() != true) {
            setVisible(true);
        }
        jTextArea.append(mensaje);
        jTextArea.append("\n");
    }
    
    void restaurarEleccion(){
        eleccion = 0;
        this.jButtonGreedy.setEnabled(true);
        this.jButtonLocalSearch.setEnabled(true);
        this.jButtonTabuSearch.setEnabled(true);
        this.jProgressBarEstado.setVisible(false);
        this.jProgressBarEstado.setValue(0);
    }
    
    
    int getEleccion(){
        return eleccion;
    }
    
    
    void setValue( int estado){
        jProgressBarEstado.setValue(jProgressBarEstado.getValue()+estado);
    }
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButtonGreedy = new javax.swing.JButton();
        jButtonLocalSearch = new javax.swing.JButton();
        jButtonTabuSearch = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jProgressBarEstado = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Práctica 1 Metaheurísticas");
        setResizable(false);

        jTextArea.setEditable(false);
        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTextArea);

        jButtonGreedy.setText("Greedy");
        jButtonGreedy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGreedyActionPerformed(evt);
            }
        });

        jButtonLocalSearch.setText("Búsqueda Local");
        jButtonLocalSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalSearchActionPerformed(evt);
            }
        });

        jButtonTabuSearch.setText("Búsqueda Tabú");
        jButtonTabuSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTabuSearchActionPerformed(evt);
            }
        });

        jButtonExit.setText("Salir");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione una heurística");

        jProgressBarEstado.setMaximum(1000);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGreedy)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLocalSearch)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTabuSearch)
                        .addGap(103, 103, 103)
                        .addComponent(jButtonExit))
                    .addComponent(jProgressBarEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit)
                    .addComponent(jButtonTabuSearch)
                    .addComponent(jButtonLocalSearch)
                    .addComponent(jButtonGreedy)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGreedyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGreedyActionPerformed
        eleccion = 1;
        jTextArea.setText("");
        this.jButtonGreedy.setEnabled(false);
        this.jButtonLocalSearch.setEnabled(false);
        this.jButtonTabuSearch.setEnabled(false);
        this.jProgressBarEstado.setVisible(true);
    }//GEN-LAST:event_jButtonGreedyActionPerformed

    private void jButtonLocalSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalSearchActionPerformed
        eleccion = 2;
        jTextArea.setText("");
        this.jButtonGreedy.setEnabled(false);
        this.jButtonLocalSearch.setEnabled(false);
        this.jButtonTabuSearch.setEnabled(false);
        this.jProgressBarEstado.setVisible(true);
    }//GEN-LAST:event_jButtonLocalSearchActionPerformed

    private void jButtonTabuSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTabuSearchActionPerformed
        eleccion = 3;
        jTextArea.setText("");
        this.jButtonGreedy.setEnabled(false);
        this.jButtonLocalSearch.setEnabled(false);
        this.jButtonTabuSearch.setEnabled(false);
        this.jProgressBarEstado.setVisible(true);
    }//GEN-LAST:event_jButtonTabuSearchActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonGreedy;
    private javax.swing.JButton jButtonLocalSearch;
    private javax.swing.JButton jButtonTabuSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBarEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
